name: pawsandpills
description: Medication manager for humans and pets
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/conflicts.json
    - assets/toxic_pets.json
    - assets/species.json
